### ISSUE TITLE
Hi im getting an error with the Preprocessing Parameters:  {(?:[^{}]*|(?R))*}

### ISSUE THREAD

**Issue by eh369** [yurtesen/zabbix_backuppc#9]
Preprocessing failed for: HTTP/1.1 200 OK..Connection: close..Transfer-Encoding: chunked..Content-Type: text/html; charset=...
1. Failed: cannot perform regular expression "{(?:[^{}]*|(?R))*}" match for value of type "none": pattern does not match

and when i test the preprocessing steps i get: 
cannot perform regular expression "{(?:[^{}]*|(?R))*}" match for value of type "none": pattern does not match

im on zabbix 6.4.5

**Comment by yurtesen** [comment]
Interesting because somebody else reported that this should be working.
https://github.com/yurtesen/zabbix_backuppc/pull/3#issuecomment-1564186538
maybe you could try without that patch?
https://github.com/yurtesen/zabbix_backuppc/pull/3/commits/7b7a8a876cc5ef94878bd1800519e5ae31a80a0b

But it looks like maybe the contents are empty? Are you using the BackupPC from master? (if they did not make a release recently, the old version had some bugs)

**Comment by eh369** [comment]
so that could be the issue then because im using the BackupPC from the backuppc/ repo , ill update to the version that you have in your repos (didnt check that earlier) thanks
